"""Add is_online to Courier

Revision ID: 30db30b2efb4
Revises: 47f7d7ce422c
Create Date: 2025-06-07 17:18:16.915915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30db30b2efb4'
down_revision = '47f7d7ce422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
