"""Add restaurant_name to orders

Revision ID: 47f7d7ce422c
Revises: 49dda376c247
Create Date: 2025-06-07 11:04:44.457383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f7d7ce422c'
down_revision = '49dda376c247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('items', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('origin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('origin')
        batch_op.drop_column('note')
        batch_op.drop_column('items')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('restaurant_name')

    # ### end Alembic commands ###
